#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Wire ~/.zshenv and ~/.zshrc into OmacOS.
#
# ~/.zshenv  — env vars (sourced by ALL zsh: scripts, editors, cron, login)
#   EDITOR, VISUAL, PATH additions, BAT_THEME
#
# ~/.zshrc   — interactive shell hooks (order matters):
#   1. mise activate              (sets up shims/PATH)
#   2. fzf + zoxide hooks
#   3. zsh-autosuggestions        (sourced BEFORE prompt)
#   4. theme zsh.zsh              (sets autosuggest + syntax colors)
#   5. starship init              (prompt)
#   6. zsh-syntax-highlighting    (absolutely LAST: wraps ZLE widgets)
#
# Both files are fully owned by OmacOS and overwritten on each run (backup
# preserved). Users add personal overrides in ~/.zshenv.local / ~/.zshrc.local.
#
set -euo pipefail

# shellcheck source=lib/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../lib/common.sh"

zshenv="$HOME/.zshenv"
zshrc="$HOME/.zshrc"

open_marker='# >>> omacos >>>'
close_marker='# <<< omacos <<<'

# Detect brew prefix for plugin source paths
brew_prefix=""
command -v brew >/dev/null 2>&1 && brew_prefix="$(brew --prefix 2>/dev/null || true)"
[[ -z "$brew_prefix" ]] && brew_prefix="/opt/homebrew"

write_file() {
  local file="$1"
  shift
  local content_fn="$1"
  if [[ -f "$file" ]]; then
    ts="$(date +%Y%m%d-%H%M%S)"
    cp "$file" "$file.bak.$ts"
    info "Backed up $file to $file.bak.$ts"
  fi
  {
    printf "%s\n" "$open_marker"
    $content_fn
    printf "%s\n" "$close_marker"
  } >"$file"
}

# --- ~/.zshenv: environment variables (all zsh invocations) ------------------
zshenv_body() {
  cat <<BLOCK
# AUTO-GENERATED by OmacOS (install/shell.sh). DO NOT EDIT.
# Overwritten on each ./install.sh run; previous version saved as .bak.
# Personal overrides: ~/.zshenv.local (never touched by OmacOS).

# Editor: Zed primary (GUI); override to nvim in SSH/headless contexts.
export EDITOR="zed --wait"
export VISUAL="\$EDITOR"

# User-local binaries (uv, pipx, cargo, etc.) take priority.
export PATH="\$HOME/.local/bin:\$PATH"

# bat theme default; themes/<name>/zsh.zsh may override via BAT_THEME.
export BAT_THEME="\${BAT_THEME:-base16}"

[[ -f "\$HOME/.zshenv.local" ]] && source "\$HOME/.zshenv.local"
BLOCK
}

# --- ~/.zshrc: interactive shell hooks (order matters) -----------------------
zshrc_body() {
  cat <<BLOCK
# AUTO-GENERATED by OmacOS (install/shell.sh). DO NOT EDIT.
# Overwritten on each ./install.sh run; previous version saved as .bak.
# Personal overrides: ~/.zshrc.local (never touched by OmacOS).

# Disable XON/XOFF flow control so Ctrl+S is available for history search.
stty -ixon 2>/dev/null || true

# 1. mise: language version manager (Node/Python/Go/Rust via rustup)
if command -v mise >/dev/null 2>&1; then
  eval "\$(mise activate zsh)"
fi

# Completion system: initialise compsys, then make Tab completion (including
# paths) case-insensitive so e.g. \`cd dow<Tab>\` completes \`Downloads\`.
autoload -Uz compinit
compinit -u 2>/dev/null || compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# 2. fzf + zoxide hooks
if command -v fzf >/dev/null 2>&1; then
  source <(fzf --zsh) 2>/dev/null || true
fi
if command -v zoxide >/dev/null 2>&1; then
  eval "\$(zoxide init zsh)"
fi

# Suppress the end-of-partial-line marker (reverse-video block in Terminal.app).
PROMPT_SP=""

# 3. zsh-autosuggestions: fish-style history suggestions
if [[ -f "$brew_prefix/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  source "$brew_prefix/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

# 4. Active theme's shell color overrides (autosuggest + syntax highlight)
if [[ -f "\$HOME/.config/omacos/theme.zsh" ]]; then
  source "\$HOME/.config/omacos/theme.zsh"
fi

# 5. Starship prompt
if command -v starship >/dev/null 2>&1; then
  eval "\$(starship init zsh)"
fi

# 6. zsh-syntax-highlighting: MUST be sourced before .zshrc.local (wraps ZLE widgets)
if [[ -f "$brew_prefix/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "$brew_prefix/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# Personal overrides: always last so user settings win over everything.
# OmacOS never edits ~/.zshrc.local.
[[ -f "\$HOME/.zshrc.local" ]] && source "\$HOME/.zshrc.local"
BLOCK
}

write_file "$zshenv" zshenv_body
ok "Wrote ~/.zshenv (env vars)"

write_file "$zshrc" zshrc_body
ok "Wrote ~/.zshrc (interactive hooks)"

note "Start a new shell or 'exec zsh' to pick up changes."
